#!/bin/bash

echo "🚀 Deploying PPT App to Render..."

echo "✅ Your repository is ready: https://github.com/sujal715/ppt-app"
echo ""
echo "🌐 Follow these steps to deploy:"
echo ""
echo "1. Go to: https://render.com"
echo "2. Sign up/Login with your GitHub account"
echo "3. Click 'New +' → 'Blueprint'"
echo "4. Connect your repository: https://github.com/sujal715/ppt-app"
echo "5. Render will automatically detect the render.yaml file"
echo "6. Click 'Apply' to start deployment"
echo ""
echo "⏳ Deployment will create:"
echo "   • Frontend: https://ppt-app-frontend.onrender.com"
echo "   • Backend: https://ppt-app-backend.onrender.com"
echo "   • Admin: https://ppt-app-frontend.onrender.com/admin"
echo "   • Database: MySQL hosted on Render"
echo ""
echo "🔐 Admin Login:"
echo "   • Username: admin"
echo "   • Password: admin"
echo ""
echo "📋 After deployment, your website will work exactly like localhost!"
echo ""
echo "🎉 Ready to deploy? Go to https://render.com now!"
