#!/bin/bash

echo "🚀 Redeploying Unified PPT App..."
echo ""

echo "✅ Changes pushed to: https://github.com/sujal715/ppt-app"
echo ""

echo "🔧 To fix the live deployment:"
echo ""
echo "1. Go to: https://render.com/dashboard"
echo "2. Find your current service (ppt-app-xrom)"
echo "3. Click on it → Settings → Delete Service"
echo "4. Click 'New +' → 'Blueprint'"
echo "5. Connect: https://github.com/sujal715/ppt-app"
echo "6. Click 'Apply'"
echo ""
echo "⏳ This will create:"
echo "   • Single URL: https://ppt-app.onrender.com"
echo "   • Unified service (Frontend + Backend + Database)"
echo ""
echo "🎯 Result: Live site will work exactly like localhost!"
echo ""
echo "🔐 Admin: https://ppt-app.onrender.com/admin"
echo "   Username: admin"
echo "   Password: admin"
echo ""
echo "📞 Ready to redeploy? Go to Render now!"
