services:
  # Single Web Service (Spring Boot + React Frontend)
  - type: web
    name: ppt-app
    runtime: java
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../clean-spring-boot && ./mvnw clean package -DskipTests
    startCommand: cd clean-spring-boot && java -jar target/mpt-0.0.1-SNAPSHOT.jar
    autoDeployTrigger: commit
    plan: starter
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: ALLOWED_ORIGINS
        value: https://ppt-app-y42f.onrender.com
