services:
  # Static Site Service
  - type: web
    name: ppt-app
    rootDir: frontend
    buildCommand: npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    plan: starter
