services:
  # Static Site Service
  - type: web
    name: ppt-app
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    plan: starter
