services:
  # Unified Web Service (Spring Boot + React Frontend)
  - type: web
    name: ppt-app
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../clean-spring-boot && ./mvnw clean package -DskipTests
    startCommand: cd clean-spring-boot && java -jar target/mpt-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: ALLOWED_ORIGINS
        value: https://ppt-app.onrender.com
    autoDeploy: true
    plan: starter
