services:
  # Frontend (React) — Static Site
  - type: web
    name: ppt-app-frontend
    runtime: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/build
    autoDeployTrigger: commit
    plan: starter
    envVars:
      - key: REACT_APP_API_URL
        value: https://ppt-app-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend (Spring Boot) — Docker
  - type: web
    name: ppt-app-backend
    runtime: docker
    dockerfilePath: ./clean-spring-boot/Dockerfile
    autoDeployTrigger: commit
    plan: starter
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: ALLOWED_ORIGINS
        value: https://ppt-app-frontend.onrender.com
